### ISSUE TITLE
I hope to use .net dependency injection to create an OllamaApiClient object

### ISSUE THREAD

**Issue by qazljlj** [awaescher/OllamaSharp#100]
Can I use .net dependency injection to create an OllamaApiClient object instead of new OllamaApiClient? And I don't seem to have a way to set the timeout of HttpClient

**Comment by awaescher** [comment]
I'd suggest to implement an own interface like `IAiService` that is not provider dependent so you can exchange the  implementation anytime and you don't have third party dependencies in your business code.

There are several alternatives to this like setting up a factory pattern to use the `IOllamaApiClient` directly. But let's go with my first approach.

Let's say you have your `OllamaAiService` that implements `IAiService`. Register this service and also an (own) options class for the uri and the model settings. 

```
var options = new OllamaOptions(); // Uri & Model, bind from appsettings.json or whatever you want

registration.Services.AddSingleton(options);
registration.Services.AddTransient<IAiService, OllamaAiService>();
```

In the `OllamaAiService` use `OllamaOptions` as injection argument. With that you can instantiate a new `OllamaApiClient` when you need it.

```
public OllamaAiService(OllamaOptions ollamaOptions, ...)
{
    OllamaOptions = ollamaOptions ?? throw new ArgumentNullException(nameof(ollamaOptions));
    ...
}

public async IAsyncEnumerable<AiChatResponse> Chat(..., [EnumeratorCancellation] CancellationToken cancellationToken)
{
    var ollama = new OllamaApiClient(OllamaOptions.Uri) { SelectedModel = OllamaOptions.Model };
    ...
}
```

Now you can use your `IAiService` with dependency injection anywhere in your application to chat, etc. 

---

> And I don't seem to have a way to set the timeout of HttpClient

There's a constructor overload that takes an http client you can preconfigure as you like.

**Comment by qazljlj** [comment]
Got it, thank you
