### ISSUE TITLE
Project File Improvements: Update Metadata and Simplify Structure

### ISSUE THREAD

**Issue by Hritikraj8804** [awaescher/OllamaSharp#101]
# Enhancement

The current OllamaSharp.csproj file for the project is functional, but there are several areas where it can be improved for better maintainability, package metadata, and project structure.

- Simplify File Paths for Additional Package Files
- Add RepositoryType for NuGet Metadata
- Set Output Path for LICENSE File
- Enable XML Documentation Generation

**Comment by awaescher** [comment]
I added the xml documentation, must have missed this earlier. Thanks.
"git" is the default repository type for the nuget metadata, I added it anyways.

Would you elaborate what you mean with these two and why you think it should be added?
- Simplify File Paths for Additional Package Files
- Set Output Path for LICENSE File

**Comment by awaescher** [comment]
Enhancements I understood were released. Please feel free to reopen this issue if you want to elaborate on the two suggestions I mentioned above.
