### ISSUE TITLE
How do you separate instruction from the content?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [awaescher/OllamaSharp#106]
To make sure the instruction is not being lost and clearly separated from the content.

**Comment by awaescher** [comment]
Would you elaborate?

**Comment by ErfolgreichCharismatisch** [comment]
Using https://ollama.com/library/[llama3:instruct](https://ollama.com/library/llama3:instruct), how do you separate instruction and content?

**Comment by awaescher** [comment]
I am still unsure what you want to achieve. My best guess is you mean the separation from the system prompt and the user prompt. 

If you want to use the `Generate()` method, you can use the overload that accepts an `GenerateRequest` which has a property `System` for the system prompt and a property `Prompt` for the user prompt as you can see [here](https://github.com/awaescher/OllamaSharp/blob/main/src/Models/Generate.cs). The design of these classes comes from the official Ollama API, see [here](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-completion).

If you use the `Chat` class, you can do it like [shown here](https://github.com/awaescher/OllamaSharpConsole/blob/main/Demos/ChatConsole.cs).

**Comment by ErfolgreichCharismatisch** [comment]
Using

```
ConversationContext context = null;

await foreach (var stream in ollama.Generate(prompt + ": " + content, context, cancellationToken))
{
	Console.WriteLine(stream.Response);
}
```

I get a result, using

```
GenerateRequest generateRequest = new GenerateRequest();
generateRequest.Prompt = content;
generateRequest.System = prompt;

await foreach (var stream in ollama.Generate(generateRequest,cancellationToken))
{
	Console.WriteLine(stream.Response);
}
```

I only get

Exception: "OllamaSharp.Models.Exceptions.OllamaException" in OllamaSharp.dll
Exception: "OllamaSharp.Models.Exceptions.OllamaException" in mscorlib.dll
Exception: "OllamaSharp.Models.Exceptions.OllamaException" in mscorlib.dll
Exception: "OllamaSharp.Models.Exceptions.OllamaException" in mscorlib.dll
Exception: "OllamaSharp.Models.Exceptions.OllamaException" in mscorlib.dll
Exception: "OllamaSharp.Models.Exceptions.OllamaException" in mscorlib.dll
Exception: "OllamaSharp.Models.Exceptions.OllamaException" in mscorlib.dll
Exception: "OllamaSharp.Models.Exceptions.OllamaException" in mscorlib.dll
