### ISSUE TITLE
Implement IChatClient (Microsoft.Extensions.AI)

### ISSUE THREAD

**Issue by awaescher** [awaescher/OllamaSharp#112]
Microsoft reached out that they'd love to have this repository to be the implementation of `Microsoft.Extensions.AI` and with that replace `Microsoft.Extensions.AI.Ollama` announced here:
 - [Introducing Microsoft.Extensions.AI Preview – Unified AI Building Blocks for .NET](https://devblogs.microsoft.com/dotnet/introducing-microsoft-extensions-ai-preview/)

To fill this gap, OllamaSharp needs to implement `IChatClient`.

**Comment by aaronpowell** [comment]
Just created a tracking on the Aspire integration to update and expose this - https://github.com/CommunityToolkit/Aspire/issues/164
