### ISSUE TITLE
Encoding incorrect for image content

### ISSUE THREAD

**Issue by JeremyLikness** [awaescher/OllamaSharp#130]
Using M.E.A.I. and passing something like this:

```csharp
var imageContent = new ImageContent(File.ReadAllBytes(), "image/jpeg");
```

Should work, but throws an exception. That's because other providers accept the data-uri format, but Ollama does not. The AbstracationsMapper should convert to pure Base64 rather then data-uri encoding it.

**Comment by JeremyLikness** [comment]
For working example:
[https://github.com/dotnet/extensions/... (MEAI)](https://github.com/dotnet/extensions/blob/9eea77d211b201c6e60c5f5074238cca08ac1ba9/src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaChatClient.cs#L361-L367)

**Comment by awaescher** [comment]
Yes, byte arrays won't work currently, I fixed that this weekend but did not push. Give me a few minutes.

**Comment by JeremyLikness** [comment]
Thank you!!!
