### ISSUE TITLE
How do I get/set the seed currently used for generating this very output?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [awaescher/OllamaSharp#145]
See title.

**Comment by awaescher** [comment]
You can pass a [seed with your request](https://github.com/awaescher/OllamaSharp/blob/5137316579d04358d0a901baa45eeeecefbddc25/src/Models/RequestOptions.cs#L145). 
Please see the [official Ollama API docs](https://github.com/ollama/ollama/blob/main/docs/api.md) for more information.
