### ISSUE TITLE
[Bug] Die Abhängigkeit "Microsoft.Extensions.AI.Abstractions" kann nicht aufgelöst werden

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [awaescher/OllamaSharp#146]
Die Abhängigkeit "Microsoft.Extensions.AI.Abstractions" kann nicht aufgelöst werden. Verwendete Quelle(n): 'nuget.org', 'Microsoft Visual Studio Offline Packages' für alle Versionen >= 4.

**Comment by awaescher** [comment]
What should this be?

**Comment by ErfolgreichCharismatisch** [comment]
Alle Versionen von OllamaSharp >= Version 4.0 haben diese Abhängigkeit. Wir können Deutsch kommunizieren.

**Comment by ErfolgreichCharismatisch** [comment]
Das kannst du auch anders formulieren, mir gefällt dein Ton nicht. Meine Fehlermeldungen sind ausreichend genau. 

Zur Sache: Die Fehlermeldung wird ausgegeben, weil die Abhängigkeit nicht vorhanden ist und die Frage ist, welche Version von Visual Studio du verwendest. Ist es eine Preview Version, Professional, Community? Denn Microsoft.Extensions.AI ist selbst relativ neu und ich habe nur etwas von einer Preview Version gelesen.
