### ISSUE TITLE
Adding a lot of messages to history, models state that we had no conversational history

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [awaescher/OllamaSharp#148]
When adding to chat history with

```
OllamaSharp.Models.Chat.Message m = new OllamaSharp.Models.Chat.Message();
m.Role = OllamaSharp.Models.Chat.ChatRole.User;
m.Content = "whatever";
chat.Messages.Add(m);
```

What limits the amount of messages and their length? Is it `context length times 4`, ie. all messages must have less than `context length times 4` combined in length?

I am asking, because when adding a lot of messages to history, the models claim that we had no previous conversation.

**Comment by awaescher** [comment]
Seems you're running out of context length indeed you can approach this by increasing `num_ctx`. Please refer to the [Ollama docs](https://github.com/ollama/ollama/blob/main/docs/modelfile.md#parameter).

**Comment by ErfolgreichCharismatisch** [comment]
As far as I know, max context length depends on the model and is not arbitrary.

**Comment by awaescher** [comment]
Of course it depends on the model, but Ollama, for example, limits the `num_ctx` by default. If you provide more context than the model can process, even `num_ctx` is useless ... but most models have far more context than I would worry about.

**Comment by ErfolgreichCharismatisch** [comment]
chat.Options.NumCtx scheint die Kontextlänge für die Ausgabe zu sein, hier geht es aber um die Eingabe.

**Comment by awaescher** [comment]
It's not just for generation. As said, please check the Ollama docs, this has nothing to do with the implementation of this repository.
