### ISSUE TITLE
Missing parameter "format" in GenerateCompletionRequest

### ISSUE THREAD

**Issue by Puresoft** [awaescher/OllamaSharp#19]
Hi, I'm missing the format parameter for JSON mode in the GenerateCompletionRequest class.

DOC: https://github.com/ollama/ollama/blob/main/docs/api.md

I'm using JSON mode for long running request, 1 request will take up to 5 minutes.
Is there a way to set the timeout?

**Comment by awaescher** [comment]
You mean this one?
> format: the format to return a response in. Currently the only accepted value is json

As it does not support any other values than `json` it is not part of the model.

As for the timeout, you should be able to simply cancel any operation with a CancellationToken.

**Comment by awaescher** [comment]
**timeout**
You can preconfigure your `HttpClient` as you wish and pass it as constructor argument to the `OllamaApiClient`. Don't forget to set the `BaseAddress` on it if doing so.

**JSON mode**
Understood. Might implement this.

**Comment by awaescher** [comment]
Fixed with #22
