### ISSUE TITLE
Should use relative paths, not absolute

### ISSUE THREAD

**Issue by faibistes** [awaescher/OllamaSharp#24]
It should use api/generate, not /api/generate.
It doesn't work if ollama has a base path (like http://ollamaserver/ollama/api/generate), which is common with reverse proxies.

**Comment by kescherCode** [comment]
I've included this in my PR #22.

**Comment by kescherCode** [comment]
Keep in mind that, if you were to use that PR, you'd have to make your api base URL end with a slash, or it will be overridden again.

**Comment by awaescher** [comment]
Fixed with #22
