### ISSUE TITLE
NO_PROXY

### ISSUE THREAD

**Issue by kpirkl** [awaescher/OllamaSharp#26]
You might want to add a note to the readme for others that sit behind a firewall that are experiencing the challenge of Proxy Service. HTTPClient under the covers supports the environment variable NO_PROXY

Adding this to my code gets it working otherwise it's very difficult to diagnose.
System.Environment.SetEnvironmentVariable("NO_PROXY", "localhost");

You can close this issue.. I just wanted to share it with you as I struggled for an hour this morning trying to determine why the code did not work from my office.

**Comment by awaescher** [comment]
Thanks for clarifying this. However I guess this is the default behavior of the .NET HttpClient, so I think think I'll add this explicitly to the readme.
