### ISSUE TITLE
Ollama support embedding models - https://ollama.com/blog/embedding-models

### ISSUE THREAD

**Issue by dinhquangsonimip** [awaescher/OllamaSharp#31]
Please support embedding models too

**Comment by awaescher** [comment]
Not sure what exactly you mean by that, the `/embeddings` endpoint is available to be used with OllamaSharp.
→ [Link](https://github.com/awaescher/OllamaSharp/blob/cdd7afcbda27a3b9460b5cd3e34df70fa244ee9f/src/OllamaApiClient.cs#L95C48-L95C66)
