### ISSUE TITLE
[BUG]: Wrong GenerateEmbeddingResponse Format

### ISSUE THREAD

**Issue by TonyWang666** [awaescher/OllamaSharp#5]
Version: OllamaSharp 1.0.2
The `GenerateEmbeddingResponse` doesn't match the actual returned json format from endpoint `api/embeddings`

I am using `OllamaSharp 1.0.2` to call endpoint `api/embeddings` with model(`llama2:70b`) and prompt. However, the returned json is  `{ "embedding": [ 1232321, 1232321, ...] } ` instead of [GenerateEmbeddingResponse](https://github.com/awaescher/OllamaSharp/blob/main/src/Models/GenerateEmbedding.cs#L18) with `{ "embeddings": [ 1232321, 1232321, ...] } `

According to the [official doc](https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-embeddings), the returned key word should be `embedding` without `s`.

**Comment by awaescher** [comment]
Nice catch, thanks. I just found out that [the docs](https://github.com/jmorganca/ollama/pull/818) where wrong about that too. 
Going to fix it.
