### ISSUE TITLE
RequestOptions model bug

### ISSUE THREAD

**Issue by r4p1er** [awaescher/OllamaSharp#52]
I encountered the following problem: I wanted to send a request to Ollama with some model parameters (mirostat, temperature, seed, etc.). For this, I used the RequestOptions model. However, when sending the request, the Ollama server crashes with a 500 Internal Server Error.

As it turned out, in the RequestOptions model, the Stop parameter is represented as string?, but the Ollama REST API expects an array of strings for this parameter, not just a single string (this can be seen in the official documentation https://github.com/ollama/ollama/blob/main/docs/api.md). Hence, the 500 Internal Server Error.

I was able to fix this problem locally by creating a custom JsonConverter<string> that splits the original string into substrings by a certain delimiter and serializes the required JSON array of strings. Then I just added the attribute [JsonConverter(typeof(StopOptionJsonConverter))] to the Stop property. And this worked for me.

**Comment by awaescher** [comment]
Guess making the property a string-Array fixes this, would you confirm?

**Comment by r4p1er** [comment]
I've tested version 2.0.8 and now it works fine
