### ISSUE TITLE
Does ProcessStreamedCompletionResponseAsync have to return nullable?

### ISSUE THREAD

**Issue by JornWildt** [awaescher/OllamaSharp#67]
The public Generate() API returns `IAsyncEnumerable<GenerateResponseStream?>` as a result of this:

    private static async IAsyncEnumerable<GenerateResponseStream?> ProcessStreamedCompletionResponseAsync() ...

But does `ProcessStreamedCompletionResponseAsync` have to return nullable? When would a single `GenerateResponseStream` element be null and what would it signal to the consumer?

**Comment by Plootie** [comment]
If the CancellationToken is cancelled before the first stream can come in I believe you'll get a null generateResponseStream

**Comment by JornWildt** [comment]
Thanks. Seems like an unnecessary complexity though. I think it would make it easier for the consumer just to return an empty stream then.

**Comment by awaescher** [comment]
Because the `System.Text.Json.JsonSerializer` returns a `TValue?`:
```csharp
public static TValue? Deserialize<TValue>(...)
```
