### ISSUE TITLE
Allow Option for adding CustomHeaders Per Request

### ISSUE THREAD

**Issue by RogerBarreto** [awaescher/OllamaSharp#72]
Currently we have a need to add Custom Headers to each request made to the Ollama API.

Would be very useful if your `RequestOptions` had an extra options for `CustomHeaders` that would be used when creating the `HttpRequestMessage`.

This functionality would be useful for all the API calls, mostly `Embed`, `Generate` and `Chat`.

**Comment by awaescher** [comment]
Is it possible to use the `OllamaApiClient` [contructor overload](https://github.com/awaescher/OllamaSharp/blob/0d894d3b7b5de6b041293ac8537d24e5c9fc89ca/src/OllamaApiClient.cs#L68) that accepts a `HttpClient` with [`DefaultRequestHeader`s`](https://learn.microsoft.com/de-de/dotnet/api/system.net.http.httpclient.defaultrequestheaders?view=net-8.0)?

**Comment by awaescher** [comment]
... bump ...

**Comment by RogerBarreto** [comment]
When we have an `httpClient` sent by the caller, we can't modify it as a bad practice (it can be used/shared by other applications), but injecting headers per each request won't change the behavior of the client outside of the context of the OllamaClient.

**Comment by awaescher** [comment]
Would #79 fit your needs?

**Comment by RogerBarreto** [comment]
@awaescher I appreciate the update, at a first glance this will fit well!
