### ISSUE TITLE
Missing release notes

### ISSUE THREAD

**Issue by dluc** [awaescher/OllamaSharp#80]
Right now it's a bit hard finding out what changed from one release to the next. It would be helpful if each release had a list of PRs/commits.

GitHub can generate the list automatically, even after the release if you want. E.g. you can edit a release:

Click the pencil:
![image](https://github.com/user-attachments/assets/4b71c15c-ef2c-4bdc-b360-f087c46f5bac)

Click "Generate release notes"
![image](https://github.com/user-attachments/assets/f3196d38-2943-4a2f-a883-3c1b611ee30d)

and save.

Note: you can edit also past releases

**Comment by awaescher** [comment]
Where do you look for the changes?

The GitHub releases have the changes logged. It's only a few changes each because of the continuous integration pipeline.

![image](https://github.com/user-attachments/assets/77e06fbd-0f91-4995-bf99-1b24b26b6557)

**Comment by dluc** [comment]
I look here https://github.com/awaescher/OllamaSharp/releases (the Releases link in the home). See for comparison this page https://github.com/microsoft/kernel-memory/releases

The pipeline should be able to generate the notes, usually there's a dedicated step. In my case I don't like the notes generated by pipelines and I follow those step I mentioned earlier.

**Comment by dluc** [comment]
looks like there's notes now, thanks :-)

**Comment by awaescher** [comment]
I added the changes earlier today 😅
