### ISSUE TITLE
Strong Name

### ISSUE THREAD

**Issue by gjactat** [awaescher/OllamaSharp#85]
Hello,
As you probably know, OllamaSharp is now used by pretty big projects (such as Microsoft SemanticKernel).
This leads me to the following issue that I have created : https://github.com/microsoft/semantic-kernel/issues/8928

Adding a Strong Name to OllamaSharp would probably resolve this issue. Is this in your plans ?
Furthermore, any signed .Net Framework assembly requires its dependencies to be signed as well. I think that this is no longer true in .net Core...

Thanks for reading and thanks for your great work!
Guillaume

**Comment by RogerBarreto** [comment]
@gjactat Thanks for bringing this issue to the OllamaSharp, indeed I was investigating came to the evidence on the **Strong Naming** problem running against .Net Framework (netstandard 2.0) versions.

![image](https://github.com/user-attachments/assets/90a02a9a-546d-4411-95df-6e2b2c658a17)

I will be following this and happy to update our `Ollama` connector to a Strongly signed version of OllamaSharp library.

**Comment by awaescher** [comment]
[OllamaSharp 3.0.10](https://github.com/awaescher/OllamaSharp/releases/tag/3.0.10) now comes with a strong name ✅

**Comment by gjactat** [comment]
Thank you @awaescher  !
