### ISSUE TITLE
Chat.Send(): allow send without new message or image

### ISSUE THREAD

**Issue by kescherCode** [awaescher/OllamaSharp#86]
If you build the chat history yourself already, having to separate out the last message in the last step of processing is kind of a hassle.

Can we get an overload of Chat.Send / Chat.SendAs that simply doesn't force adding another message onto the existing message history?

**Comment by awaescher** [comment]
I guess I don't understand this. Would you elaborate?

**Comment by kescherCode** [comment]
Chat.Send forces you to add a message (either just text or along with an image). However, Chat.SetMessages already allows you to set message history.

Compared to e.g. the OpenAI SDK, there you **have** to pass the full history, always, as their ChatClient does not keep track of message history on its own.

**Comment by awaescher** [comment]
So you want to keep track of all of this by yourself? You can by using the [`Chat()` method](https://github.com/awaescher/OllamaSharp/blob/d0bc64791548f35b7367e3cb43761dbe11cb389d/src/OllamaApiClient.cs#L166) that takes a `ChatRequest` and sends it to Ollama. This is 1:1 the endpoint `/chat`.

What you mentioned is the helper class [`Chat`](https://github.com/awaescher/OllamaSharp/blob/d0bc64791548f35b7367e3cb43761dbe11cb389d/src/Chat.cs#L95) which only exists to track everything for you to make it easier to build an interactive chat. 

However, using this helper class is not necessary - you can use the [`Chat()` method](https://github.com/awaescher/OllamaSharp/blob/d0bc64791548f35b7367e3cb43761dbe11cb389d/src/OllamaApiClient.cs#L166) directly and build your own `ChatRequest` each time.

**Comment by kescherCode** [comment]
Fair. I think using the helper class is worthwhile for other reasons, but that's workable.
