### ISSUE TITLE
Improve Pagination with Page Selection on Packages Page

### ISSUE THREAD

**Issue by Mefisto04** [awaescher/OllamaSharp#99]
**Description:**

The current pagination system only allows users to move between pages using "Next" and "Previous" buttons, which can be inefficient. I propose adding a page selection option, allowing users to jump directly to any page, improving overall navigation and user experience.

**Action Items:**

- Add a page selection feature to the pagination.
- Ensure it works with the search functionality.

**Screenshot:**
![image](https://github.com/user-attachments/assets/1a1ec104-e278-4eaa-9a22-d25178b26e8f)

Please assign this issue to me so I can start working on it.

---

**Comment by awaescher** [comment]
Sorry but what are you talking about?

**Comment by Mefisto04** [comment]
![image](https://github.com/user-attachments/assets/de9525c0-4c71-4375-9065-78ecdfddae5a)
like this pagination, it will improve overall navigation and user experience.

**Comment by awaescher** [comment]
I guess you misunderstood something about this project
